// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: teams.sql

package gensql

import (
	"context"

	"github.com/lib/pq"
)

const teamCreate = `-- name: TeamCreate :exec
INSERT INTO teams ("team", "users")
VALUES ($1, $2)
`

type TeamCreateParams struct {
	Team  string
	Users []string
}

func (q *Queries) TeamCreate(ctx context.Context, arg TeamCreateParams) error {
	_, err := q.db.ExecContext(ctx, teamCreate, arg.Team, pq.Array(arg.Users))
	return err
}

const teamDelete = `-- name: TeamDelete :exec
DELETE FROM teams
WHERE team = $1
`

func (q *Queries) TeamDelete(ctx context.Context, team string) error {
	_, err := q.db.ExecContext(ctx, teamDelete, team)
	return err
}

const teamGet = `-- name: TeamGet :one
SELECT team, users FROM teams
WHERE team = $1
`

type TeamGetRow struct {
	Team  string
	Users []string
}

func (q *Queries) TeamGet(ctx context.Context, team string) (TeamGetRow, error) {
	row := q.db.QueryRowContext(ctx, teamGet, team)
	var i TeamGetRow
	err := row.Scan(&i.Team, pq.Array(&i.Users))
	return i, err
}

const teamUpdate = `-- name: TeamUpdate :exec
UPDATE teams
SET users = $1
WHERE team = $2
`

type TeamUpdateParams struct {
	Users []string
	Team  string
}

func (q *Queries) TeamUpdate(ctx context.Context, arg TeamUpdateParams) error {
	_, err := q.db.ExecContext(ctx, teamUpdate, pq.Array(arg.Users), arg.Team)
	return err
}

const teamsForUserGet = `-- name: TeamsForUserGet :many
SELECT team FROM teams
WHERE $1::TEXT = ANY("users")
`

func (q *Queries) TeamsForUserGet(ctx context.Context, email string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, teamsForUserGet, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var team string
		if err := rows.Scan(&team); err != nil {
			return nil, err
		}
		items = append(items, team)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
