run:
  go: '1.21'
  timeout: 10m

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    - gofumpt
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - gochecknoglobals
    - gocognit
    - gomnd
    - goprintffuncname
    - prealloc
    - rowserrcheck
    - wsl

issues:
  exclude-use-default: false
  exclude:
    # should have a package comment, unless it's in another file for this package (golint)
    - 'in another file for this package'

linters-settings:
  dupl:
    threshold: 400
  lll:
    line-length: 170
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0

output:
  format: colored-line-number