version: "2"
run:
  go: "1.23"
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - godot
    - godox
    - tagalign
    - tagliatelle
    - varnamelen
  settings:
    dupl:
      threshold: 400
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 170
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - dogsled
          - funlen
        path: (.+)_test.go
      - path: (.+)\.go$
        text: in another file for this package
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  new-from-rev: HEAD
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
