version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knorten
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"

networks: 
  default:
    name: cloudbuild
    external: true
