oauth:
    client_id: # Set through env var KNORTEN_OAUTH_CLIENT_ID
    client_secret: # Set through env var KNORTEN_OAUTH_CLIENT_SECRET
    tenant_id: # Set through env var KNORTEN_OAUTH_TENANT_ID
    redirect_url: https://knorten.dev.knada.io/oauth2/callback
gcp:
    project: knada-dev
    region: europe-north1
    zone: europe-north1-b
cookies:
    redirect:
        name: redirecturi
        max_age: 3600
        path: /
        domain: knorten.dev.knada.io
        same_site: Lax
        secure: true
        http_only: false
    oauth_state:
        name: oauth_state
        max_age: 3600
        path: /
        domain: knorten.dev.knada.io
        same_site: Lax
        secure: true
        http_only: false
    session:
        name: knorten_session
        max_age: 86400
        path: /
        domain: knorten.dev.knada.io
        same_site: Lax
        secure: true
        http_only: false
helm:
    repository_config: /root/.config/helm/repositories.yaml
    airflow_chart_version: 1.11.0
    jupyter_chart_version: 3.2.1
server:
    hostname: 0.0.0.0
    port: 8080
postgres:
    host: 127.0.0.1
    port: 5432
    user_name: knorten
    password: # Set through env var KNORTEN_POSTGRES_PASSWORD
    database_name: knorten
    ssl_mode: disable
kubernetes:
    context: ""
db_enc_key: # Set through env var KNORTEN_DB_ENC_KEY
admin_group_id: f2816319-7db0-4061-8d0c-5ddbe232d60c
session_key: # Set through env var KNORTEN_SESSION_KEY
login_page: https://knorten.dev.knada.io/
top_level_domain: dev.knada.io
dry_run: false
debug: false
