name: Build and push knorten image to GAR

on:
  workflow_dispatch:
  push:

env:
  IMAGE: europe-north1-docker.pkg.dev/knada-gcp/knada-north/knorten

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.21' # The Go version to download (if necessary) and use.
        check-latest: true
    - run: make check
    - run: go install honnef.co/go/tools/cmd/staticcheck@latest
    - run: staticcheck ./...

  build-and-push:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v4
    - name: Google auth
      uses: google-github-actions/auth@v2
      with:
        project_id: knada-gcp
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
    - name: Create image tag
      run: |
        imagename=europe-north1-docker.pkg.dev/knada-gcp/knada-north/knorten
        echo "IMAGE=$imagename:$(date '+%Y-%m-%d')-$(git --no-pager log -1 --pretty=%h)" >> $GITHUB_ENV
    - name: Build and push Dockerimage
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE }}
    - name: Update imagetag in k8s manifest
      working-directory: k8s/overlays/dev
      run: |
        kustomize edit set image ${{ env.IMAGE }}
        cat kustomization.yaml
